### ISSUE TITLE
Package doesn't work with Laravel 5.8

### ISSUE THREAD

**Issue by ErriourMe** [mostafaznv/recaptcha#2]
In time of installing I've got an error:

> Problem 1
    - Installation request for mostafaznv/recaptcha ^1.1 -> satisfiable by mostafaznv/recaptcha[1.1.0].
    - Conclusion: remove laravel/framework v5.8.13
    - Conclusion: don't install laravel/framework v5.8.13
    - mostafaznv/recaptcha 1.1.0 requires laravel/framework 5.3.* || 5.4.* || 5.5.* || 5.6.* || 5.7.* -> satisfiable by laravel/framework[5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.3.x-dev, v5.8.13].
    - Can only install one of: laravel/framework[5.4.x-dev, v5.8.13].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.8.13].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.8.13].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.13].
    - Installation request for laravel/framework (locked at v5.8.13, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.13].

Can you fix dependency? I think it will works with 5.8

**Comment by mostafaznv** [comment]
Package updated 
please require/update to version 1.1.1
