### ISSUE TITLE
Validation always return captcha error

### ISSUE THREAD

**Issue by eternalBlast** [mostafaznv/recaptcha#3]
Hi, i tried to make the recaptcha v3 similar to this readme for validation. 
```
$this->validate($request, [
        'g-recaptcha-response' => 'required|recaptcha:home,0.5',
 ]);
```
It always return captcha error by validation "Captcha error! try again later or contact site admin." (I already added the custom validation message though). What's wrong with this? Please help. Thanks in advance.

**Comment by mostafaznv** [comment]
Hi.
I checked your code, It's OK and I couldn't see any error on that.
It seems you are getting error from Google's server, to clarify what's going on, please validate the recaptcha code [manually](https://github.com/mostafaznv/recaptcha#validate-score-manually) and check the score you are getting from server.

**Comment by eternalBlast** [comment]
Hi @mostafaznv. I checked it like this.
```
if($score > 0.5) {
      dd("pass");
} else {
      dd("fail");
}
```
Just ignore the dd function. I just intend to check whether if it pass or not. And the result is it pass. But, when i using re-submit data without back it is fail. Do the mechanism like that? Thanks in advance.

**Comment by mostafaznv** [comment]
You can't re-submit data without refresh page. because you are sending a recaptcha token that is used before and is not valid anymore.

**Comment by eternalBlast** [comment]
Ok thanks. I think the problem is just with the custom validation of laravel. Thanks a lot.
