### ISSUE TITLE
Wrong Facade path in readme

### ISSUE THREAD

**Issue by Mushr0000m** [mostafaznv/recaptcha#5]
Great work !

Just a little mistake in the doc the path to the alias is : 
`'Recaptcha'     => Mostafaznv\Recaptcha\Recaptcha::class,`
Should be : 
`'Recaptcha'     => Mostafaznv\Recaptcha\Facades\Recaptcha::class,`

**Comment by mostafaznv** [comment]
Thank you so much for report
Fixed
